### ISSUE TITLE
[BUG]: 

### ISSUE THREAD

**Issue by smallka1** [A-kirami/nonebot-plugin-aidraw#26]
### 报告清单

- [X] 我已仔细阅读并了解上述注意事项。
- [X] 我已使用最新版本测试过，确定问题依旧存在。
- [X] 我确定在 [GitHub Issues](../issues) 中没有相同或相似的问题。
- [ ] 我愿意帮助修复此问题。（这会将您指定为此问题的受理人并自动创建修复分支）

### 影响版本

0.6.3

### 问题描述

PS D:\robot\ai>  d:; cd 'd:\robot\ai'; & 'C:\Users\smallka\AppData\Local\Programs\Python\Python39\python.exe' 'c:\Users\smallka\.vscode\extensions\ms-python.python-2022.16.1\pythonFiles\lib\python\debugpy\adapter/../..\debugpy\launcher' '8458' '--' 'd:\robot\ai\bot.py' 
10-19 21:48:11 [SUCCESS] nonebot | NoneBot is initializing...
10-19 21:48:11 [INFO] nonebot | Current Env: prod
10-19 21:48:11 [SUCCESS] nonebot | Succeeded to import "nonebot.plugins.echo"
10-19 21:48:11 [ERROR] nonebot | Failed to import "nonebot_plugin_aidraw"
Traceback (most recent call last):
  File "d:\robot\ai\bot.py", line 27, in <module>
    nonebot.load_from_toml("pyproject.toml")
  File "C:\Users\smallka\AppData\Local\Programs\Python\Python39\lib\site-packages\nonebot\plugin\load.py", line 119, in load_from_toml
    return load_all_plugins(plugins, plugin_dirs)
  File "C:\Users\smallka\AppData\Local\Programs\Python\Python39\lib\site-packages\nonebot\plugin\load.py", line 53, in load_all_plugins
    return manager.load_all_plugins()
  File "C:\Users\smallka\AppData\Local\Programs\Python\Python39\lib\site-packages\nonebot\plugin\manager.py", line 128, in load_all_plugins
    return set(
  File "C:\Users\smallka\AppData\Local\Programs\Python\Python39\lib\site-packages\nonebot\plugin\manager.py", line 129, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.list_plugins()))
> File "C:\Users\smallka\AppData\Local\Programs\Python\Python39\lib\site-packages\nonebot\plugin\manager.py", line 104, in load_plugin
    module = importlib.import_module(name)
  File "C:\Users\smallka\AppData\Local\Programs\Python\Python39\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "C:\Users\smallka\AppData\Local\Programs\Python\Python39\lib\site-packages\nonebot\plugin\manager.py", line 194, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "C:\Users\smallka\AppData\Local\Programs\Python\Python39\lib\site-packages\nonebot_plugin_aidraw\__init__.py", line 1, in <module>
    from . import draw, count
  File "C:\Users\smallka\AppData\Local\Programs\Python\Python39\lib\site-packages\nonebot_plugin_aidraw\draw.py", line 17, in <module>
    from nonebot.adapters.onebot.v11.helpers import (
ImportError: cannot import name 'autorevoke_send' from 'nonebot.adapters.onebot.v11.helpers' (C:\Users\smallka\AppData\Local\Programs\Python\Python39\lib\site-packages\nonebot\adapters\onebot\v11\helpers.py)
10-19 21:48:11 [WARNING] __main__ | Always use `nb run` to start the bot instead of manually running!
10-19 21:48:11 [SUCCESS] nonebot | Running NoneBot...
10-19 21:48:11 [INFO] uvicorn | Started server process [25588]
10-19 21:48:11 [INFO] uvicorn | Waiting for application startup.
10-19 21:48:11 [INFO] uvicorn | Application startup complete.
10-19 21:48:11 [INFO] uvicorn | Uvicorn running on http://127.0.0.1:8080 (Press CTRL+C to quit)

### 重现步骤

使用nb指令安装插件后运行报错

**Comment by A-kirami** [comment]
你没有安装 onebot 适配器 自行手动安装即可
