### ISSUE TITLE
[BUG]: 开clash，不开全局，开了之后就没法出图，关了可以，必复现

### ISSUE THREAD

**Issue by atriatri20** [A-kirami/nonebot-plugin-aidraw#37]
### 报告清单

- [X] 我已仔细阅读并了解上述注意事项。
- [X] 我已使用最新版本测试过，确定问题依旧存在。
- [X] 我确定在 [GitHub Issues](../issues) 中没有相同或相似的问题。
- [ ] 我愿意帮助修复此问题。（这会将您指定为此问题的受理人并自动创建修复分支）

### 影响版本

0.6.x

### 问题描述

10-29 22:55:37 [INFO] nonebot | Event will be handled by Matcher(type='message', module=nonebot_plugin_aidraw.draw)
10-29 22:55:37 [INFO] nonebot | Matcher(type='message', module=nonebot_plugin_aidraw.draw) running complete
10-29 22:55:37 [ERROR] nonebot | Running Matcher(type='message', module=nonebot_plugin_aidraw.draw) failed.
Traceback (most recent call last):
  File "c:\users\18749\appdata\local\programs\python\python38\lib\site-packages\anyio\streams\tls.py", line 130, in _call_sslobject_method
    result = func(*args)
  File "c:\users\18749\appdata\local\programs\python\python38\lib\ssl.py", line 944, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLSyscallError: Some I/O error occurred (_ssl.c:1131)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\users\18749\appdata\local\programs\python\python38\lib\site-packages\httpcore\_exceptions.py", line 8, in map_exceptions
    yield
  File "c:\users\18749\appdata\local\programs\python\python38\lib\site-packages\httpcore\backends\asyncio.py", line 76, in start_tls
    raise exc
  File "c:\users\18749\appdata\local\programs\python\python38\lib\site-packages\httpcore\backends\asyncio.py", line 67, in start_tls
    ssl_stream = await anyio.streams.tls.TLSStream.wrap(
  File "c:\users\18749\appdata\local\programs\python\python38\lib\site-packages\anyio\streams\tls.py", line 122, in wrap    await wrapper._call_sslobject_method(ssl_object.do_handshake)
  File "c:\users\18749\appdata\local\programs\python\python38\lib\site-packages\anyio\streams\tls.py", line 151, in _call_sslobject_method
    raise BrokenResourceError from exc
anyio.BrokenResourceError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\18749\appdata\local\programs\python\python38\lib\site-packages\httpx\_transports\default.py", line 60, in map_httpcore_exceptions
    yield
  File "c:\users\18749\appdata\local\programs\python\python38\lib\site-packages\httpx\_transports\default.py", line 353, in handle_async_request
    resp = await self._pool.handle_async_request(req)
  File "c:\users\18749\appdata\local\programs\python\python38\lib\site-packages\httpcore\_async\connection_pool.py", line 253, in handle_async_request
    raise exc
  File "c:\users\18749\appdata\local\programs\python\python38\lib\site-packages\httpcore\_async\connection_pool.py", line 237, in handle_async_request
    response = await connection.handle_async_request(request)
  File "c:\users\18749\appdata\local\programs\python\python38\lib\site-packages\httpcore\_async\http_proxy.py", line 258, in handle_async_request
    connect_response = await self._connection.handle_async_request(
  File "c:\users\18749\appdata\local\programs\python\python38\lib\site-packages\httpcore\_async\connection.py", line 86, in handle_async_request
    raise exc
  File "c:\users\18749\appdata\local\programs\python\python38\lib\site-packages\httpcore\_async\connection.py", line 63, in handle_async_request
    stream = await self._connect(request)
  File "c:\users\18749\appdata\local\programs\python\python38\lib\site-packages\httpcore\_async\connection.py", line 150, in _connect
    stream = await stream.start_tls(**kwargs)
  File "c:\users\18749\appdata\local\programs\python\python38\lib\site-packages\httpcore\backends\asyncio.py", line 76, in start_tls
    raise exc
  File "c:\users\18749\appdata\local\programs\python\python38\lib\contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "c:\users\18749\appdata\local\programs\python\python38\lib\site-packages\httpcore\_exceptions.py", line 12, in map_exceptions
    raise to_exc(exc)
httpcore.ConnectError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\users\18749\appdata\local\programs\python\python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\18749\appdata\local\programs\python\python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\18749\AppData\Local\Programs\Python\Python38\Scripts\nb.exe\__main__.py", line 7, in <module>
    sys.exit(main())
  File "c:\users\18749\appdata\local\programs\python\python38\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\18749\appdata\local\programs\python\python38\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "c:\users\18749\appdata\local\programs\python\python38\lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\18749\appdata\local\programs\python\python38\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\18749\appdata\local\programs\python\python38\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "c:\users\18749\appdata\local\programs\python\python38\lib\site-packages\nb_cli\commands\main.py", line 30, in run
    run_bot(file, app)
  File "c:\users\18749\appdata\local\programs\python\python38\lib\site-packages\nb_cli\handlers\deploy.py", line 25, in run_bot
    nonebot.run(app=f"{module_name}:{app}")
  File "c:\users\18749\appdata\local\programs\python\python38\lib\site-packages\nonebot\__init__.py", line 273, in run
    get_driver().run(*args, **kwargs)
  File "c:\users\18749\appdata\local\programs\python\python38\lib\site-packages\nonebot\drivers\fastapi.py", line 172, in run
    uvicorn.run(
  File "c:\users\18749\appdata\local\programs\python\python38\lib\site-packages\uvicorn\main.py", line 576, in run
    server.run()
  File "c:\users\18749\appdata\local\programs\python\python38\lib\site-packages\uvicorn\server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "c:\users\18749\appdata\local\programs\python\python38\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "c:\users\18749\appdata\local\programs\python\python38\lib\asyncio\base_events.py", line 603, in run_until_complete
    self.run_forever()
  File "c:\users\18749\appdata\local\programs\python\python38\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()
  File "c:\users\18749\appdata\local\programs\python\python38\lib\asyncio\base_events.py", line 570, in run_forever
    self._run_once()
  File "c:\users\18749\appdata\local\programs\python\python38\lib\asyncio\base_events.py", line 1859, in _run_once
    handle._run()
  File "c:\users\18749\appdata\local\programs\python\python38\lib\asyncio\events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "c:\users\18749\appdata\local\programs\python\python38\lib\site-packages\nonebot\message.py", line 142, in _check_matcher
    await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
> File "c:\users\18749\appdata\local\programs\python\python38\lib\site-packages\nonebot\message.py", line 186, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "c:\users\18749\appdata\local\programs\python\python38\lib\site-packages\nonebot\internal\matcher.py", line 716, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "c:\users\18749\appdata\local\programs\python\python38\lib\site-packages\nonebot\internal\matcher.py", line 688, in simple_run
    await handler(
  File "c:\users\18749\appdata\local\programs\python\python38\lib\site-packages\nonebot\dependencies\__init__.py", line 108, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "c:\users\18749\appdata\local\programs\python\python38\lib\site-packages\nonebot_plugin_aidraw\draw.py", line 148, in novel_draw_handle
    res = await client.get(
  File "c:\users\18749\appdata\local\programs\python\python38\lib\site-packages\httpx\_client.py", line 1751, in get
    return await self.request(
  File "c:\users\18749\appdata\local\programs\python\python38\lib\site-packages\httpx\_client.py", line 1527, in request    return await self.send(request, auth=auth, follow_redirects=follow_redirects)
  File "c:\users\18749\appdata\local\programs\python\python38\lib\site-packages\httpx\_client.py", line 1614, in send
    response = await self._send_handling_auth(
  File "c:\users\18749\appdata\local\programs\python\python38\lib\site-packages\httpx\_client.py", line 1642, in _send_handling_auth
    response = await self._send_handling_redirects(
  File "c:\users\18749\appdata\local\programs\python\python38\lib\site-packages\httpx\_client.py", line 1679, in _send_handling_redirects
    response = await self._send_single_request(request)
  File "c:\users\18749\appdata\local\programs\python\python38\lib\site-packages\httpx\_client.py", line 1716, in _send_single_request
    response = await transport.handle_async_request(request)
  File "c:\users\18749\appdata\local\programs\python\python38\lib\site-packages\httpx\_transports\default.py", line 353, in handle_async_request
    resp = await self._pool.handle_async_request(req)
  File "c:\users\18749\appdata\local\programs\python\python38\lib\contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "c:\users\18749\appdata\local\programs\python\python38\lib\site-packages\httpx\_transports\default.py", line 77, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ConnectError

**Comment by atriatri20** [comment]
已解决，clash里面要把设置的类型改成pac模式
