### ISSUE TITLE
[BUG]: 求助

### ISSUE THREAD

**Issue by Passerby-D** [A-kirami/nonebot-plugin-aidraw#40]
### 报告清单

- [X] 我已仔细阅读并了解上述注意事项。
- [X] 我已使用最新版本测试过，确定问题依旧存在。
- [X] 我确定在 [GitHub Issues](../issues) 中没有相同或相似的问题。
- [X] 我愿意帮助修复此问题。（这会将您指定为此问题的受理人并自动创建修复分支）

### 影响版本

最新版本

### 问题描述

单独导入插件可正常使用
但当和haruka_bot一起使用的时候，就会报错
tortoise.exceptions.ConfigurationError: Unable to get db settings for alias 'default'. Please check if the config dict contains this alias and try again

### 重现步骤

同时导入haruka_bot和nonebot_plugin_aidraw

### 预期行为

bot正常运行

### 实际行为

报错
tortoise.exceptions.ConfigurationError: Unable to get db settings for alias 'default'. Please check if the config dict contains this alias and try again

### 日志信息

11-07 02:21:00 [ERROR] uvicorn | Traceback (most recent call last):
  File "C:\Users\DShuai\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\tortoise\connection.py", line 113, in get   
    return storage[conn_alias]
KeyError: 'default'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\DShuai\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\tortoise\connection.py", line 76, in _get_db_info
    return self.db_config[conn_alias]
KeyError: 'default'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\DShuai\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\starlette\routing.py", line 635, in lifespan    async with self.lifespan_context(app):
  File "C:\Users\DShuai\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\starlette\routing.py", line 530, in __aenter__
    await self._router.startup()
  File "C:\Users\DShuai\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\starlette\routing.py", line 612, in startup 
    await handler()
  File "C:\Users\DShuai\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\nonebot_plugin_aidraw\database.py", line 104, in init
    await Tortoise.init(config)
  File "C:\Users\DShuai\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\tortoise\__init__.py", line 574, in init    
    cls._init_apps(apps_config)
  File "C:\Users\DShuai\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\tortoise\__init__.py", line 417, in _init_apps
    cls._build_initial_querysets()
  File "C:\Users\DShuai\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\tortoise\__init__.py", line 440, in _build_initial_querysets
    model._meta.finalise_model()
  File "C:\Users\DShuai\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\tortoise\models.py", line 308, in finalise_model
    self._generate_filters()
  File "C:\Users\DShuai\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\tortoise\models.py", line 476, in _generate_filters
    get_overridden_filter_func = self.db.executor_class.get_overridden_filter_func
  File "C:\Users\DShuai\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\tortoise\models.py", line 288, in db        
    return connections.get(self.default_connection)
  File "C:\Users\DShuai\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\tortoise\connection.py", line 115, in get   
    connection: BaseDBAsyncClient = self._create_connection(conn_alias)
  File "C:\Users\DShuai\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\tortoise\connection.py", line 90, in _create_connection
    db_info = self._get_db_info(conn_alias)
  File "C:\Users\DShuai\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\tortoise\connection.py", line 78, in _get_db_info
    raise ConfigurationError(
tortoise.exceptions.ConfigurationError: Unable to get db settings for alias 'default'. Please check if the config dict contains this alias and try again

11-07 02:21:00 [ERROR] uvicorn | Application startup failed. Exiting.

### 额外补充

其实我有在issues里面看到类似的问题，但碍于我水平有限，无法举一反三，还望大佬指点一下

**Comment by DGHOSTI** [comment]
和你的情况一样，他们说是数据库冲突了

**Comment by A-kirami** [comment]
此项目已停止维护并归档
